### ISSUE TITLE
Error 1.18.2

### ISSUE THREAD

**Issue by lostINParadies** [serversigns/ServerSigns#54]
https://pastebin.com/YmKudQU7

Error 1.18.2. No Crash - works normally

**Comment by EpiCanard** [comment]
Hello,

Did you try to execute the command `/openmenu schnellreise.yml herter113` in the chat ?

It seems the error come from BetterGUI.

**Comment by lostINParadies** [comment]
I Tried. No error

**Comment by EpiCanard** [comment]
The error come from the library [XSeries](https://github.com/CryptoMorin/XSeries) that [BetterGUI](https://github.com/BetterGUI-MC/BetterGUI) use.

It doesn't find a specific method `net.minecraft.server.network.PlayerConnection.sendPacket`. I don't really understand why because it should try to find the method `net.minecraft.server.network.PlayerConnection.a`.

Do you use the last version of BetterGUI ?

Anyway it's definitely not an issue with ServerSigns but an issue with BetterGUI ou XSeries (a version too old for example).

**Comment by lostINParadies** [comment]
I am using the latest version of Bettergui. Thanks for help - I am asking the dev of this plugin.

**Comment by EpiCanard** [comment]
You're welcome, good luck with BetterGUI.

I close the issue, feel free to reopen it if necessary.
